server:
  port: 8088
  forward-headers-strategy: true
  undertow:
    io-threads: 2
    worker-threads: 36
    buffer-size: 1024
    directBuffers: true
  servlet:
    session:
      timeout: 86400
spring:
  transaction:
    rollback-on-commit-failure: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySql配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://112.124.203.218:3306/houserent?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: houserent
    password: YyPyhGDWt6BNDWSH
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  mail:
    host: smtp.sina.com
    port: 465
    username: memcpy0@sina.com
    password: 97e3d34d6482962f
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.javaDemo.houserent.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

logging:
  file: ./logs/log.log
  level:
    org:
      springframework:
        boot:
          autoconfigure: error

shiro:
  userNativeSessionManager: true

application:
  version: 1.0.2
#  staticCdnUrl:
